services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sleep infinity
    # ports: # let vscode handle port forwarding
    #   - "5173:5173"
    #   - "5165:5165"

volumes:
  devcontainer-node-modules:
  devcontainer-dotnet-tools:

networks:
  dev:
    driver: bridge